export { default as AnimationHome } from './AnimationHome/AnimationHome';
export * from './CardHomeLeft';
export * from './CardHomeRight';
export { default as ContentLeft } from './ContentLeft/ContentLeft';
export { default as ContentRight } from './ContentRight/ContentRight';
export { default as DescriptionRightHome } from './DescriptionRightHome/DescriptionRightHome';
export { default as ModalApp } from './Modals/ModalApp/ModalApp';
export { default as ModalBranding } from './Modals/ModalBranding/ModalBranding';
export { default as ModalMarketing } from './Modals/ModalMarketing/ModalMarketing';
export { default as ModalSocialMedia } from './Modals/ModalSocialMedia/ModalSocialMedia';
export { default as ModalUx } from './Modals/ModalUx/ModalUx';
export { default as ModalWebApps } from './Modals/ModalWebApps/ModalWebApps';
export * from './Modals';
export { default as TitleHome } from './TitleHome/TitleHome';
